apiVersion: apps/v1
kind: Deployment
metadata:
  name: DotnetCoreTest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: DotnetCoreTest
  template:
    metadata:
      labels:
        app: DotnetCoreTest
    spec:
      containers:
      - name: dockerbuvana123/my-dotnet-app
        image: testimage
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetcoretest
spec:
  type: LoadBalancer
  selector:
    app: dotnetcoretest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
